name: scalapay_assessment
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pine: ^1.0.4
  provider: ^6.1.5
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  talker: ^4.9.0
  talker_dio_logger: ^4.9.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.3
  dio: ^5.8.0+1
  http_mock_adapter: ^0.6.1
  retrofit: ^4.4.2
  data_fixture_dart: ^3.0.0
  freezed_annotation: ^3.0.0
  freezed: ^3.0.6
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ">=8.0.0 <10.0.0"
  json_serializable: ^6.9.5
  build_runner: ^2.5.3
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
